default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: 5819Lincoln@

development:
  <<: *default
  database: hello_rails_development

test:
  <<: *default
  database: hello_rails_test

production:
  <<: *default
  database: hello_rails_production
  username: postgres
  password: 5819Lincoln@